### ISSUE TITLE
Throws type error in a typescript project

### ISSUE THREAD

**Issue by dejavu1987** [jshemas/openGraphScraper#253]
**Describe the bug**
When I call og() function (default export from the library) I see following type error on a typescript project.
```
"TypeError: (0 , open_graph_scraper_1.default) is not a function
```

**To Reproduce**
In a typescript file.
```
import ogs from 'open-graph-scraper';
const { result } = await ogs({ url });
```

**Expected behavior**
It should return the open graph data

**Actual behavior**
throwing the type error

**Additional context**
It works for non typescript / plain js project.

 - OS: MacOS
 - Node Version: 20.17.0
 - openGraphScraper Version: 6.8.2

**Comment by dejavu1987** [comment]
Please have a look at this fork. https://github.com/jshemas/openGraphScraper/compare/jshemas:master...OscarBarrett:feature/full-esm-build?expand=1

It would be nice if it could be merged.

**Comment by jshemas** [comment]
Hello, what does your `tsconfig.json` look like?

**Comment by jshemas** [comment]
Example `tsconfig.json`:
```
{
  "compilerOptions": {
    "target": "es2017",
    "module": "commonjs",
    "declaration": true,
    "outDir": "./build",
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "strict": true,
    "skipLibCheck": true
  },
  "include": ["index.ts"]
}
```

Working code example:

```
import ogs from 'open-graph-scraper';

const getAPI = async () => {
  const { result } = await ogs({  url: 'http://ogp.me/' });
  console.log('result:', result);
};

getAPI()
```

This will output:

```
result: {
  success: true,
  ogTitle: 'Open Graph protocol',
  ogType: 'website',
  ogUrl: 'https://ogp.me/',
  ogDescription: 'The Open Graph protocol enables any web page to become a rich object in a social graph.',
  fbAppId: '115190258555800',
  ogImage: [
    {
      height: '300',
      type: 'image/png',
      url: 'https://ogp.me/logo.png',
      width: '300',
      alt: 'The Open Graph logo'
    }
  ],
  charset: 'utf-8',
  requestUrl: 'http://ogp.me/'
}
```

If I use `github:OscarBarrett/openGraphScraper#feature/full-esm-build`, I get the following error with the above code.

```
/home/user/src/testing/commonjs/node_modules/ts-node/dist/index.js:851
            return old(m, filename);
                   ^
Error [ERR_REQUIRE_ESM]: require() of ES Module /home/user/src/testing/commonjs/node_modules/open-graph-scraper/dist/cjs/index.js from /home/user/src/testing/commonjs/index.ts not supported.
index.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use dynamic import() which is available in all CommonJS modules, or change "type": "module" to "type": "commonjs" in /home/user/src/testing/commonjs/node_modules/open-graph-scraper/package.json to treat all .js files as CommonJS (using .mjs for all ES modules instead).

    at require.extensions.<computed> [as .js] (/home/user/src/testing/commonjs/node_modules/ts-node/dist/index.js:851:20)
    at Object.<anonymous> (/home/user/src/testing/commonjs/index.ts:6:46)
    at m._compile (/home/user/src/testing/commonjs/node_modules/ts-node/dist/index.js:857:29)
    at require.extensions.<computed> [as .ts] (/home/user/src/testing/commonjs/node_modules/ts-node/dist/index.js:859:16)
    at phase4 (/home/user/src/testing/commonjs/node_modules/ts-node/dist/bin.js:466:20)
    at bootstrap (/home/user/src/testing/commonjs/node_modules/ts-node/dist/bin.js:54:12)
    at main (/home/user/src/testing/commonjs/node_modules/ts-node/dist/bin.js:33:12)
    at Object.<anonymous> (/home/user/src/testing/commonjs/node_modules/ts-node/dist/bin.js:579:5) {
  code: 'ERR_REQUIRE_ESM'
}
```

**Comment by jshemas** [comment]
Closing this for now. Please reopen when you have more info on the issue.
