### ISSUE TITLE
Integration issue

### ISSUE THREAD

**Issue by Vinu-MysteriousTechVision** [jshemas/openGraphScraper#43]
Loading dependency graph, done.
error: bundling: UnableToResolveError: Unable to resolve module `url` from `../SampleOGP/node_modules/open-graph-scraper/app.js`: 
Module does not exist in the module map or in these directories:
  ../SampleOGP/node_modules/open-graph-scraper/node_modules
,   ../SampleOGP/node_modules

This might be related to https://github.com/facebook/react-native/issues/4968
To resolve try the following:
  1. Clear watchman watches: `watchman watch-del-all`.
  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
  3. Reset packager cache: `rm -fr $TMPDIR/react-*` or `npm start -- --reset-cache`.
    at ResolutionRequest._resolveNodeDependency (../SampleOGP/node_modules/react-native/packager/src/node-haste/DependencyGraph/ResolutionRequest.js:470:11)
    at ResolutionRequest.resolveDependency (../SampleOGP/node_modules/react-native/packager/src/node-haste/DependencyGraph/ResolutionRequest.js:135:29)
    at dependencyNames.map.name (../SampleOGP/node_modules/react-native/packager/src/node-haste/DependencyGraph/ResolutionRequest.js:142:59)
    at Array.map (native)
    at ResolutionRequest.resolveModuleDependencies (../SampleOGP/node_modules/react-native/packager/src/node-haste/DependencyGraph/ResolutionRequest.js:142:42)
    at module.readFresh.then (../SampleOGP/node_modules/react-native/packager/src/node-haste/DependencyGraph/ResolutionRequest.js:182:40)
    at process._tickCallback (internal/process/next_tick.js:109:7)

**build environment:
node: v7.7.3,
react-native: react-native-cli: 2.0.1,
OS: MAC-OS,
react: 16.0.0-alpha.12,
react-native: 0.45.1**

**Comment by jshemas** [comment]
I'm not really sure what you are trying to say. The module `url` I use is apart of Node.js 

https://nodejs.org/api/url.html

**Comment by Vinu-MysteriousTechVision** [comment]
@jshemas 
Thanks for the reply, understand that the problems of node.js. but I can't resolve the error.

> Unable to resolve module `URL` 

If you have any suggestion to solve the issue, kindly help for this.

**Comment by jshemas** [comment]
I would have to see your codebase or code snippet to help debug this.

**Comment by jshemas** [comment]
going to close this for now
