### ISSUE TITLE
Cannot read property 'startsWith' of undefined

### ISSUE THREAD

**Issue by fakhir-shad** [jshemas/openGraphScraper#94]
Having trouble using ``openGraphScraper``, even with the default example i am getting error, i have tried different versions from 4.00 to 4.2.0 but received the same error. I have also tried removing the ``node_modules`` and ``package-lock.json``. I am using node 10.16.3
Using this example
```
const ogs = require('open-graph-scraper');
const options = { url: 'https://www.npmjs.com/package/open-graph-scraper' };
ogs(options)
  .then((data) => {
    const { error, result, response } = data;
    console.log('error:', error);  // This is returns true or false. True if there was a error. The error it self is inside the results object.
    console.log('result:', result); // This contains all of the Open Graph results
    console.log('response:', response); // This contains the HTML of page
  })
```
I am getting this error
```
   { error: true
    result: {
      "success": false,
      "requestUrl": "https://www.npmjs.com/package/open-graph-scraper",
      "error": "Cannot read property 'startsWith' of undefined",
      "errorDetails": {
        "name": "RequestError"
      }
    }}

```
![Screenshot from 2020-06-26 16-44-54](https://user-images.githubusercontent.com/18720182/85855010-f2a0ec80-b7ce-11ea-845d-b81849e62109.png)

**Comment by jshemas** [comment]
Using your code example I am unable to reproduce the problem. I'm using Node `v10.16.3` and here are my resultes:
```
{ ogDescription:
   'Node.js scraper module for Open Graph and Twitter Card info',
  ogTitle: 'open-graph-scraper',
  ogUrl: 'https://www.npmjs.com/package/open-graph-scraper',
  ogSiteName: 'npm',
  twitterCard: 'summary',
  twitterUrl: 'https://www.npmjs.com/package/open-graph-scraper',
  twitterTitle: 'npm: open-graph-scraper',
  twitterDescription:
   'Node.js scraper module for Open Graph and Twitter Card info',
  ogImage:
   { url:
      'https://static.npmjs.com/338e4905a2684ca96e08c7780fc68412.png',
     width: null,
     height: null,
     type: 'png' },
  ogDate: '2020-06-23T23:52:25.488Z',
  requestUrl: 'https://www.npmjs.com/package/open-graph-scraper',
  success: true }
```

What operating system are you running this on? Do you see this with other websites?

Can you try running this with `open-graph-scraper@4.2.1` ? I added a extra check here https://github.com/jshemas/openGraphScraper/commit/fe499dda95b3faa3d37e2e5516c5d0ddfe3cf14c but I don't think that is the issue.

**Comment by jshemas** [comment]
I got this error when messing with `https://www.npmjs.com/package/proxy-agent`, is your app using a proxy agent?
```
result: { success: false,
  requestUrl: 'https://www.npmjs.com/package/open-graph-scraper',
  error: 'Cannot read property \'startsWith\' of undefined',
  errorDetails:
   { RequestError: Cannot read property 'startsWith' of undefined
       at PromisableRequest._makeRequest (C:\openGraphScraper\node_modules\got\dist\source\core\index.js:1010:19)
       at Request (C:\openGraphScraper\node_modules\got\dist\source\core\index.js:270:28)
       at urlToOptions (internal/url.js:1259:28)
       at Object.request (https.js:279:15)
       at Object.<anonymous> (C:\openGraphScraper\node_modules\agent-base\patch-core.js:25:22)
       at C:\openGraphScraper\node_modules\socks-proxy-agent\node_modules\agent-base\patch-core.js:23:20
       at PromisableRequest._makeRequest (C:\openGraphScraper\node_modules\got\dist\source\core\index.js:982:43)
       at Request (C:\openGraphScraper\node_modules\got\dist\source\core\index.js:270:28)
       at process._tickCallback (internal/process/next_tick.js:68:7) name: 'RequestError', code: undefined, timings: undefined } }
```

**Comment by jshemas** [comment]
This might also be a issue with `got`, it only supports node `10.19.0` and up. 

https://github.com/sindresorhus/got/blob/master/package.json#L10

**Comment by jshemas** [comment]
Closing due to inactivity and node10 has reached it's end of life.
